project:
  type: book
  output-dir: _site


number-sections: true
lang: de
book:
  title: "Schneller, schöner, stressfreier Lehren"
  subtitle: "Vom Recherchieren zur interaktiven Vorlesung"
  author: "Prof. Dr. Christian Kraus"
  date: "last-modified"
  chapters:
    - index.qmd
    - Phase1.qmd
    - Phase2.qmd
    - Phase3.qmd
    - Phase4.qmd
    - Phase5.qmd
    - Phase6.qmd
    - Abschluss.qmd
  appendices:
    - Anhang.qmd
    - OneQuart.qmd
    

  
  # Navigation & Suche
  sidebar:
    style: "docked"
    background: light # Passt gut zu deinem thws-grey/orange
    collapse-level: 1
    search: true
  repo-url: https://github.com/c-kraus/KI_Lehre_Workshop
  repo-actions: [issue]
  sharing: [linkedin]
 
   
format:
  moodle-html: default
  



# Globale Optionen für Code-Zellen (Tech-Stack)
execute:
  echo: false
  warning: false